version: '3.8'
services:
  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: winn
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./app/data:/data/db
    networks:
      - moviesnet
  
  app_backend:
    build: ./backend/app
    restart: always
    environment:
      - 'PORT=3001'
    ports:
      - 3001:3001
    depends_on:
      - database
    networks:
      - moviesnet

  app_frontend:
    build: ./frontend/
    restart: always
  ports:
      - 3001:3001
  depends_on:
    - app_backend
  networks:
    - moviesnet

networks:
  moviesnet:
    driver: bridge 

volumes:
  mongo-data: