version: '3.8'
services:
  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: winn
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./backend/app/data:/data/db
    networks:
      - moviesnet
  
  app_backend:
    build: ./backend/app
    restart: always
    environment:
      - 'PORT=3001'
    ports:
      - 3001:3001
    depends_on:
      - database
    networks:
      - moviesnet

  app_frontend:
    build: ./frontend/
    restart: always
    environment:
      - 'REACT_APP_API_URL=http://localhost:3001/'
    ports:
      - 3000:3000
    depends_on:
      - app_backend
    networks:
      - moviesnet

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3002:3002
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
  
networks:
  moviesnet:
    driver: bridge 

volumes:
  mongo-data:
  prometheus-data:
  grafana-data: