version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: winn
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
  app:
    build: ./app
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
volumes:
  mongo-data: