version: '3.8'
services:
  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: winn
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./app/data:/data/db
  
  app:
    build: ./app
    restart: always
    environment:
      - 'PORT=3001'
    ports:
      - 3001:3001
    depends_on:
      - database
volumes:
  mongo-data: